spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${YOUNG_TECH_DB_URL}
    username: ${YOUNG_TECH_DB_USER}
    password: ${YOUNG_TECH_DB_PASSWORD}
  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: false
    show-sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    banner-mode: off
