spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/young_tech
    username: root
    password: PapasFritas22@
  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: false
    show-sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB