spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${YOUNG_TECH_DB_URL}
    username: ${YOUNG_TECH_DB_USER}
    password: ${YOUNG_TECH_DB_PASSWORD}
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/
server:
  servlet:
    context-path: ${api.base-url}

logging:
  level:
    org:
      springframework:

        #INFO LOGGING
        security: INFO
        web: INFO

        #DEBUG LOGGING
#        security: DEBUG
#        web: DEBUG

        #TRACE LOGGING
#        security: TRACE
#        web: TRACE



api:
  version: 1
  base-url: /api/v1
  web-client: http://localhost:3000

crypto:
  keys:
    -
      private-key-der-path: ${YOUNG_TECH_PRIVATE_KEY_DER_PATH}
      public-key-der-path: ${YOUNG_TECH_PUBLIC_KEY_DER_PATH}
      jwk-id: key1
